### ISSUE TITLE
react-native link react-native-lock problem

### ISSUE THREAD

**Issue by hasanmumin** [auth0/react-native-lock#110]
Hi.
* node v7.0.0
* react 15.4.1
* react-native 0.39.2
* react-native-lock 0.4.0

i just create new project with "react-native init" command,
than i install react-native-lock
than i run "react-native link react-native-lock" command.

```
Adding Podfile to iOS project
Installing Pods
node_modules/react-native-lock/bin/cocoapods.sh: line 45: pod: command not found
/Users/xxxx/xxxx/xxxx/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${ command }" command`);
        ^
Error: Error occured during executing "node_modules/react-native-lock/bin/cocoapods.sh" command
    at ChildProcess.prelink (/Users/xxxx/xxxx/xxxx/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

thank you.

**Comment by tiempham** [comment]
Did you fix it? Can you tell me how to fix it. Thank you.

**Comment by hasanmumin** [comment]
Hi @tiempham yes, i just install cocoapods. Than i run command again.

**Comment by tiempham** [comment]
Thank @hasanmumin!
