### ISSUE TITLE
cannot install react-native-lock

### ISSUE THREAD

**Issue by F4b1n0u** [auth0/react-native-lock#120]
so I simply tried
```
$ react-native init plop
$ npm intall --save react-native-lock
$ react-native link react-native-lock
```

and I get
```
Preparing to link react-native-lock for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-install info Linking react-native-lock android dependency 
rnpm-install info Android module react-native-lock has been successfully linked 
rnpm-install info Linking react-native-lock ios dependency 
rnpm-install info iOS module react-native-lock has been successfully linked 
Checking Podfile in iOS project (/Users/userName/Downloads/plop/plop/ios/Podfile)
Adding Podfile to iOS project
Installing Pods
Analyzing dependencies
[!] The dependency `Lock (~> 1.26)` is not used in any concrete target.
The dependency `Lock/TouchID` is not used in any concrete target.
The dependency `Lock/SMS` is not used in any concrete target.
The dependency `Lock/Email` is not used in any concrete target.
/Users/userName/Downloads/plop/plop/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node_modules/react-native-lock/bin/cocoapods.sh" command
    at ChildProcess.prelink (/Users/username/Downloads/plop/plop/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

by the way, the init generate me this package.json
```
{
  "name": "plop",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "~15.4.0",
    "react-native": "0.41.2",
    "react-native-lock": "^0.4.0"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "~15.4.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

is anyone have an idea ?

**Comment by F4b1n0u** [comment]
after
- using the [podfile](https://github.com/auth0/Mobile-Samples.React/blob/master/Classic/Lock/ios/Podfile) of example project of auth0
- using cocoaPods.app instead of the command line
- following this [instructions](https://github.com/auth0/react-native-lock#cocoapods-warning)
I succeed to go further.

**Comment by tiempham** [comment]
Try to open .xcworkspace folder in xcode and run. I have same issues  https://github.com/auth0/react-native-lock/issues/116.

**Comment by F4b1n0u** [comment]
it works !!!!
cheers guys
